services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: asistencias
      MYSQL_USER: asistuser
      MYSQL_PASSWORD: asistpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - asist_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: asistuser
      PMA_PASSWORD: asistpass
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - asist_network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - asist_network

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=asistencias
      - DJANGO_DB_USER=asistuser
      - DJANGO_DB_PASSWORD=asistpass
      - DJANGO_MQTT_BROKER=mosquitto
      - DJANGO_MQTT_PORT=1883
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mosquitto
    networks:
      - asist_network

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://localhost:8000/api
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules   # <- esta línea evita que se sobreescriba node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - asist_network

volumes:
  db_data:

networks:
  asist_network:
    driver: bridge 