# Generated by Django 5.2.6 on 2025-09-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoAsistencia',
            fields=[
                ('idEstadoAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('idInstitucion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='asistencias.institucion')),
            ],
            options={
                'unique_together': {('nombre', 'institucion')},
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencias.estadoasistencia')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencias.institucion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.persona')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idTipoPersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_persona', to='asistencias.institucion')),
            ],
            options={
                'unique_together': {('nombre', 'institucion')},
            },
        ),
        migrations.CreateModel(
            name='PersonaInstitucion',
            fields=[
                ('idPersonaInstitucion', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencias.curso')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.institucion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='asistencias.persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencias.tipopersona')),
            ],
            options={
                'unique_together': {('persona', 'institucion', 'tipo', 'curso')},
            },
        ),
    ]
