# Generated by Django 5.2.4 on 2025-07-02 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoAsistencia',
            fields=[
                ('idEstadoAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idTipoPersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('identificadorFacial', models.CharField(max_length=100, unique=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencias.curso')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencias.tipopersona')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('idAsistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencias.estadoasistencia')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.persona')),
            ],
        ),
    ]
