# Generated by Django 5.2.4 on 2025-07-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='fecha_hora',
            new_name='fechaHora',
        ),
    ]
