# Generated by Django 5.2.6 on 2025-09-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0002_curso_nivel_alter_persona_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nivel',
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
