# Generated by Django 5.2.10 on 2026-01-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0003_remove_curso_nivel_alter_persona_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='personas/'),
        ),
    ]
