# Generated by Django 5.2.10 on 2026-01-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0004_persona_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
