# Generated by Django 5.2.10 on 2026-01-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0005_alter_persona_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
