# Generated by Django 5.2.10 on 2026-01-27 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0008_curso_fecha_fin_curso_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencias.horario'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='llegada_tarde_minutos',
            field=models.IntegerField(default=0),
        ),
    ]
