# Generated by Django 5.2.10 on 2026-01-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0009_asistencia_horario_asistencia_llegada_tarde_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
