# Generated by Django 5.2.10 on 2026-02-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0010_persona_telefono_emergencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='horarios',
        ),
    ]
