# Generated by Django 5.2.11 on 2026-02-20 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0011_remove_persona_horarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictoIdentidad',
            fields=[
                ('idConflicto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_recibido', models.CharField(max_length=200)),
                ('fechaHora', models.DateTimeField(auto_now_add=True)),
                ('foto_recibida', models.TextField(blank=True, null=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('persona_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflictos', to='asistencias.persona')),
            ],
        ),
    ]
