# Generated by Django 5.2.11 on 2026-02-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0012_conflictoidentidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='foto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
