# Generated by Django 5.2.11 on 2026-02-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0013_asistencia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='tipo',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], default='Entrada', max_length=10),
        ),
        migrations.AddField(
            model_name='persona',
            name='requiere_salida',
            field=models.BooleanField(default=False),
        ),
    ]
