# Generated by Django 5.2.11 on 2026-02-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0014_asistencia_tipo_persona_requiere_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='salida_temprano_minutos',
            field=models.IntegerField(default=0),
        ),
    ]
