# Generated by Django 5.2.11 on 2026-02-22 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0016_data_default_tipos_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='persona_institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_personalizados', to='asistencias.personainstitucion'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='asistencias.curso'),
        ),
        migrations.CreateModel(
            name='DiaNoLaborable',
            fields=[
                ('idDia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('aplica_a_todos', models.BooleanField(default=True, help_text='Si es verdadero, aplica a toda la institución')),
                ('cursos_afectados', models.ManyToManyField(blank=True, to='asistencias.curso')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencias.institucion')),
                ('tipos_persona_afectados', models.ManyToManyField(blank=True, to='asistencias.tipopersona')),
            ],
            options={
                'unique_together': {('fecha', 'institucion')},
            },
        ),
    ]
