# Generated by Django 5.2.11 on 2026-02-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0017_horario_persona_institucion_alter_horario_curso_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dianolaborable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dianolaborable',
            name='personas_afectadas',
            field=models.ManyToManyField(blank=True, to='asistencias.persona'),
        ),
    ]
