# Generated by Django 5.2.11 on 2026-02-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0018_alter_dianolaborable_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dianolaborable',
            old_name='fecha',
            new_name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='dianolaborable',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Si es nulo, aplica sólo a fecha_inicio', null=True),
        ),
    ]
