# Generated by Django 5.2.11 on 2026-02-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0019_rename_fecha_dianolaborable_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='justificado',
            field=models.BooleanField(default=False, help_text='Si es verdadero, la falta/tardanza cuenta como presente en las estadísticas'),
        ),
    ]
