# Generated by Django 5.2.11 on 2026-03-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0020_add_justificado_to_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_referencia_semana_a', models.DateField(help_text='Una fecha conocida que cae en Semana A. El sistema calcula automáticamente si la semana actual es A o B.')),
            ],
            options={
                'verbose_name': 'Configuración de Semana',
                'verbose_name_plural': 'Configuración de Semana',
            },
        ),
        migrations.AddField(
            model_name='horario',
            name='semana',
            field=models.CharField(choices=[('Todas', 'Todas'), ('A', 'Semana A'), ('B', 'Semana B')], default='Todas', max_length=5),
        ),
        migrations.AlterField(
            model_name='persona',
            name='requiere_salida',
            field=models.BooleanField(default=True),
        ),
    ]
