# Generated by Django 5.2.12 on 2026-03-10 21:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0023_historicalconfiguracionsemana_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SincronizacionDispositivo',
            fields=[
                ('idSincronizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('personas_encontradas', models.IntegerField(default=0)),
                ('personas_nuevas', models.IntegerField(default=0)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSincronizacionDispositivo',
            fields=[
                ('idSincronizacion', models.IntegerField(blank=True, db_index=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('personas_encontradas', models.IntegerField(default=0)),
                ('personas_nuevas', models.IntegerField(default=0)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, editable=False)),
                ('completada', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sincronizacion dispositivo',
                'verbose_name_plural': 'historical sincronizacion dispositivos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
