# Generated by Django 5.2.12 on 2026-03-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0024_sincronizaciondispositivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictoidentidad',
            name='id_persona_nueva',
            field=models.IntegerField(blank=True, help_text='ID de la persona nueva detectada que generó el conflicto', null=True),
        ),
        migrations.AddField(
            model_name='historicalconflictoidentidad',
            name='id_persona_nueva',
            field=models.IntegerField(blank=True, help_text='ID de la persona nueva detectada que generó el conflicto', null=True),
        ),
    ]
