# Generated by Django 5.2.12 on 2026-03-12 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0025_add_id_persona_nueva_to_conflicto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tipopersona',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='historicalpersonainstitucion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='historicaltipopersona',
            name='institucion',
        ),
        migrations.AlterUniqueTogether(
            name='personainstitucion',
            unique_together={('persona', 'institucion', 'curso')},
        ),
        migrations.AddField(
            model_name='historicalpersona',
            name='tipo_persona',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asistencias.tipopersona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personas', to='asistencias.tipopersona'),
        ),
        migrations.AlterField(
            model_name='historicaltipopersona',
            name='nombre',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tipopersona',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='tipopersona',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='personainstitucion',
            name='tipo',
        ),
    ]
