# Generated by Django 5.2.12 on 2026-03-12 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0026_alter_tipopersona_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personainstitucion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='conflictoidentidad',
            name='id_persona_nueva',
        ),
        migrations.RemoveField(
            model_name='historicalconflictoidentidad',
            name='id_persona_nueva',
        ),
        migrations.RemoveField(
            model_name='historicalpersona',
            name='tipo_persona',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipo_persona',
        ),
        migrations.AddField(
            model_name='historicalpersonainstitucion',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asistencias.tipopersona'),
        ),
        migrations.AddField(
            model_name='personainstitucion',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='asistencias.tipopersona'),
        ),
        migrations.AlterField(
            model_name='historicaltipopersona',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipopersona',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='personainstitucion',
            unique_together={('persona', 'institucion', 'tipo', 'curso')},
        ),
    ]
