# Generated by Django 5.2.12 on 2026-03-12 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0027_alter_personainstitucion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflictoidentidad',
            name='id_persona_nueva',
            field=models.IntegerField(blank=True, help_text='ID de la persona más nueva que genera el conflicto', null=True),
        ),
        migrations.AddField(
            model_name='historicalconflictoidentidad',
            name='id_persona_nueva',
            field=models.IntegerField(blank=True, help_text='ID de la persona más nueva que genera el conflicto', null=True),
        ),
        migrations.AlterField(
            model_name='historicalpersonainstitucion',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asistencias.tipopersona'),
        ),
        migrations.AlterField(
            model_name='personainstitucion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asistencias.tipopersona'),
        ),
    ]
