# Generated by Django 5.2.12 on 2026-03-14 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0028_add_id_persona_nueva_conflicto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhorario',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='materia',
        ),
    ]
