# Generated by Django 5.2.12 on 2026-03-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0029_remove_historicalhorario_materia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhorario',
            name='materia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='materia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
