# Generated by Django 5.2.12 on 2026-03-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0030_historicalhorario_materia_horario_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhorario',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='materia',
        ),
    ]
