# Generated by Django 5.2.12 on 2026-03-19 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0031_remove_historicalhorario_materia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransicionAnioLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('revertido', models.BooleanField(default=False)),
                ('datos_reversion', models.JSONField(help_text='Lista de objetos con: idRol, idCursoAnterior')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transiciones de Año Lectivo',
                'ordering': ['-fecha'],
            },
        ),
    ]
