# Generated by Django 5.2.12 on 2026-03-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0032_transicionaniolectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], help_text='Entrada/Salida si fue un scan real del lector. Null si fue generado automáticamente (ausente, no pasó salida).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalasistencia',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], help_text='Entrada/Salida si fue un scan real del lector. Null si fue generado automáticamente (ausente, no pasó salida).', max_length=20, null=True),
        ),
    ]
