# Generated by Django 5.2.12 on 2026-03-20 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencias', '0033_tipo_nullable_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='cursos_profesor', to=settings.AUTH_USER_MODEL),
        ),
    ]
