# Mosquitto Configuration for AsistencIA

# Permite conexiones anónimas (sin user/password)
allow_anonymous true

# Listener en el puerto estándar MQTT
listener 1883
protocol mqtt

# Listener WebSockets (Corregido: debe especificar protocolo justo después)
listener 9001
protocol websockets

# Logging (Reducido para optimizar en producción)
log_type error
log_type warning
log_type notice
log_dest stdout

# Optimizaciones de Red
set_tcp_nodelay true
connection_messages true

# Persistencia y tiempos (ayuda si hay micro-cortes)
persistence true
persistence_location /mosquitto/data/
# Mantener mensajes QoS 1 por 24 horas si el cliente se desconecta (60 * 60 * 24 = 86400)
persistent_client_expiration 1d
